### Site Settings ###
title               : Ross F Koby
description         : >-
                      "I'm in the 4th year of my PhD in chemistry, currently focused on making new inorganic and organometallic molecules using mechanochemistry."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : kobyrf/kobyrf.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Ross Koby
  image             :
#  behance           : your_username
# dribbble          : your_username
  email             : ross.f.koby@vanderbilt.edu
#  facebook          : your_username
  github            : kobyrf.github.io
# gitlab            : your_username
# instagram         : your_username
  linkedin          : https://www.linkedin.com/in/ross-koby/
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : "@rawssk0be"
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"



### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
